name    'rocha-voms'
version '0.1.0'
source 'git://github.com/rochaporto/puppet-voms.git'
author 'rocha'
license 'Apache License, Version 2.0 (the "License")'
summary 'Resources for managing a gLite Virtual Organization Membership Service (VOMS) client and server installation'
description 'This modules provides classes and definitions required to manage and properly configure a gLite service or client supporting authorization using the gLite Virtual Organization Membership Service (VOMS).'
project_page 'http://glite.org'
dependency 'puppetlabs/stdlib', '>=2.2.1'
